### ISSUE TITLE
How to fix the covariance matrix?

### ISSUE THREAD

**Issue by YaweiZhao** [alshedivat/gpml#1]
Hi,

I do not want to the hyper-parameters in the covariance function are optimized during the process of inference. Could you know how to fix the covariance matrix?

**Comment by alshedivat** [comment]
If you don't want to optimize hyperparameters, simply don't call the `minimize` function. By default, inference methods do not optimizer hyperparameters. For details, please refer to the [original docs](http://www.gaussianprocess.org/gpml/code/matlab/doc/).
